{ ... }:

{

  services.xserver.displayManager.lightdm.greeters.tiny.extraConfig = ''
    /* GTK UI CSS */
    static const gchar *style =
    "window {"
          "background-image: url(\"/etc/nixos/background.jpg\");"
          "background-position: center;" 
    "}"
    "window * {"
        "font: 12px \"tewi2a\";"
        "-gtk-dpi: 131;"
    "}"
    "#prompt_box {"
        "background-color: #414141;"
        "margin: 50px 650px 50px 650px;"
        "padding: 25px 0 25px 0;"
        "border-right: 15px solid #e2a76d;"
    "}"
    "label {"
        "color: #e2a76d;"
        "margin-right: 25px;"
    "}"
    "entry {"
        "color: #e2a76d;"
        "background-color: #414141;"
        "caret-color: #e2a76d;"
        "box-shadow: 2px 2px #414141 inset;"
    "}"
    "#message_label {"
        "color: red;"
    "}";
    /* GTK UI XML*/
    static const gchar *ui =
    "<?xml version='1.0' encoding='UTF-8'?>"
    "<interface>"
      "<requires lib='gtk+' version='3.20'/>"
      "<object class='GtkWindow' id='login_window'>"
        "<property name='name'>login_window</property>"
        "<property name='can_focus'>False</property>"
        "<property name='resizable'>False</property>"
        "<property name='accept_focus'>False</property>"
        "<property name='decorated'>False</property>"
        "<child>"
          "<placeholder/>"
        "</child>"
        "<child>"
          "<object class='GtkBox' id='login_box'>"
            "<property name='name'>login_box</property>"
            "<property name='visible'>True</property>"
            "<property name='can_focus'>False</property>"
            "<property name='valign'>center</property>"
            "<property name='vexpand'>True</property>"
            "<property name='orientation'>vertical</property>"
            "<child>"
              "<object class='GtkBox' id='prompt_box'>"
                "<property name='name'>prompt_box</property>"
                "<property name='visible'>True</property>"
                "<property name='can_focus'>False</property>"
                "<property name='spacing'>15</property>"
                "<property name='homogeneous'>True</property>"
                "<child>"
                  "<object class='GtkLabel' id='prompt_label'>"
                    "<property name='name'>prompt_label</property>"
                    "<property name='visible'>True</property>"
                    "<property name='can_focus'>False</property>"
                    "<property name='halign'>end</property>"
                  "</object>"
                  "<packing>"
                    "<property name='expand'>False</property>"
                    "<property name='fill'>True</property>"
                    "<property name='position'>0</property>"
                  "</packing>"
                "</child>"
                "<child>"
                  "<object class='GtkEntry' id='prompt_entry'>"
                    "<property name='name'>prompt_entry</property>"
                    "<property name='visible'>True</property>"
                    "<property name='can_focus'>True</property>"
                    "<property name='halign'>start</property>"
                    "<property name='has_frame'>False</property>"
                    "<property name='max_width_chars'>15</property>"
                    "<property name='primary_icon_activatable'>False</property>"
                    "<property name='secondary_icon_activatable'>False</property>"
                    "<signal name='activate' handler='login_cb' swapped='no'/>"
                  "</object>"
                  "<packing>"
                    "<property name='expand'>False</property>"
                    "<property name='fill'>True</property>"
                    "<property name='position'>1</property>"
                  "</packing>"
                "</child>"
              "</object>"
              "<packing>"
                "<property name='expand'>False</property>"
                "<property name='fill'>True</property>"
                "<property name='position'>0</property>"
              "</packing>"
            "</child>"
            "<child>"
              "<object class='GtkLabel' id='message_label'>"
                "<property name='name'>message_label</property>"
                "<property name='visible'>True</property>"
                "<property name='can_focus'>False</property>"
                "<property name='halign'>center</property>"
                "<property name='width_chars'>25</property>"
                "<property name='max_width_chars'>50</property>"
              "</object>"
              "<packing>"
                "<property name='expand'>False</property>"
                "<property name='fill'>True</property>"
                "<property name='position'>1</property>"
              "</packing>"
            "</child>"
          "</object>"
        "</child>"
      "</object>"
    "</interface>";
  '';
}
